# Generated by Django 5.0.7 on 2024-07-27 10:13

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=1, upload_to=main.utils.UniqueNameImageModelMixin.get_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default=2, upload_to=main.utils.UniqueNameImageModelMixin.get_upload_path),
            preserve_default=False,
        ),
    ]
