# Generated by Django 5.0.7 on 2024-07-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_photo_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.employee'),
        ),
    ]
